"""add_new_evidence_sources

Revision ID: ba9a48942f8d
Revises: 001
Create Date: 2026-05-20 06:48:01.501254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9a48942f8d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('fold_change', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('expression_level', sa.String(length=20), nullable=True),
    sa.Column('tissue_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expression_data_disease_id'), 'expression_data', ['disease_id'], unique=False)
    op.create_index(op.f('ix_expression_data_id'), 'expression_data', ['id'], unique=False)
    op.create_index(op.f('ix_expression_data_target_id'), 'expression_data', ['target_id'], unique=False)
    op.create_table('reactome_pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.String(length=50), nullable=False),
    sa.Column('pathway_name', sa.String(length=255), nullable=True),
    sa.Column('pathway_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactome_pathways_id'), 'reactome_pathways', ['id'], unique=False)
    op.create_index(op.f('ix_reactome_pathways_target_id'), 'reactome_pathways', ['target_id'], unique=False)
    op.create_table('string_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('interactor_gene', sa.String(length=50), nullable=False),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('network_distance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_string_interactions_id'), 'string_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_string_interactions_target_id'), 'string_interactions', ['target_id'], unique=False)
    op.drop_constraint('drugs_chembl_id_key', 'drugs', type_='unique')
    op.drop_index('ix_drugs_chembl_id', table_name='drugs')
    op.create_index(op.f('ix_drugs_chembl_id'), 'drugs', ['chembl_id'], unique=True)
    op.add_column('evidence_records', sa.Column('string_score', sa.Float(), nullable=True))
    op.add_column('evidence_records', sa.Column('expression_score', sa.Float(), nullable=True))
    op.add_column('evidence_records', sa.Column('reactome_score', sa.Float(), nullable=True))
    op.drop_constraint('targets_target_id_key', 'targets', type_='unique')
    op.drop_index('ix_targets_target_id', table_name='targets')
    op.create_index(op.f('ix_targets_target_id'), 'targets', ['target_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_target_id'), table_name='targets')
    op.create_index('ix_targets_target_id', 'targets', ['target_id'], unique=False)
    op.create_unique_constraint('targets_target_id_key', 'targets', ['target_id'])
    op.drop_column('evidence_records', 'reactome_score')
    op.drop_column('evidence_records', 'expression_score')
    op.drop_column('evidence_records', 'string_score')
    op.drop_index(op.f('ix_drugs_chembl_id'), table_name='drugs')
    op.create_index('ix_drugs_chembl_id', 'drugs', ['chembl_id'], unique=False)
    op.create_unique_constraint('drugs_chembl_id_key', 'drugs', ['chembl_id'])
    op.drop_index(op.f('ix_string_interactions_target_id'), table_name='string_interactions')
    op.drop_index(op.f('ix_string_interactions_id'), table_name='string_interactions')
    op.drop_table('string_interactions')
    op.drop_index(op.f('ix_reactome_pathways_target_id'), table_name='reactome_pathways')
    op.drop_index(op.f('ix_reactome_pathways_id'), table_name='reactome_pathways')
    op.drop_table('reactome_pathways')
    op.drop_index(op.f('ix_expression_data_target_id'), table_name='expression_data')
    op.drop_index(op.f('ix_expression_data_id'), table_name='expression_data')
    op.drop_index(op.f('ix_expression_data_disease_id'), table_name='expression_data')
    op.drop_table('expression_data')
    # ### end Alembic commands ###
